name: Bug Report
description: Report something that is not working correctly
labels: [bug]
body:
  - type: input
    id: summary
    attributes:
      label: Short Summary
      placeholder: "Laser won't trigger alarm"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: Explain what you expected to happen vs what happened.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      value: |
        1. ...
        2. ...
        3. ...
      render: text

  - type: textarea
    id: environment
    attributes:
      label: Hardware / Setup
      placeholder: |
        Board Model: (e.g. Arduino Uno)
        Sensor type: (e.g. Laser module + LDR)
