name: Build and Attach Firmware

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PlatformIO
        uses: actions/setup-python@v4
      - run: pip install platformio

      - name: Build all PlatformIO environments (UNO + NANO)
        run: platformio run

      - name: Upload compiled firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firmware-binaries
          path: |
            .pio/build/uno/firmware.hex
            .pio/build/nanoatmega328/firmware.hex

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: firmware-binaries
          path: ./firmware

      - name: Create Release and Attach Files
        uses: softprops/action-gh-release@v1
        with:
          files: "./firmware/*.hex"
